export const PRODUCT_LIST_ALL_REQUEST = "PRODUCT_LIST_ALL_REQUEST";
export const PRODUCT_LIST_ALL_SUCCESS = "PRODUCT_LIST_ALL_SUCCESS";
export const PRODUCTS_LIST_ALL_FAIL = "PRODUCTS_LIST_ALL_FAIL";

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCTS_LIST_FAIL = "PRODUCTS_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCTS_DETAILS_FAIL = "PRODUCTS_DETAILS_FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCTS_DELETE_FAIL";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCTS_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCTS_CREATE_RESET";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCTS_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUCTS_UPDATE_RESET";

export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCTS_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCTS_CREATE_REVIEW_RESET";

export const PRODUCT_TOP_REQUEST = "PRODUCT_TOP_REQUEST";
export const PRODUCT_TOP_SUCCESS = "PRODUCT_TOP_SUCCESS";
export const PRODUCT_TOP_FAIL = "PRODUCTS_TOP_FAIL";

export const PRODUCT_SIMILAR_REQUEST = "PRODUCT_SIMILAR_REQUEST";
export const PRODUCT_SIMILAR_SUCCESS = "PRODUCT_SIMILAR_SUCCESS";
export const PRODUCT_SIMILAR_FAIL = "PRODUCTS_SIMILAR_FAIL";

export const PRODUCT_CHOOSE_REQUEST = "PRODUCT_CHOOSE_REQUEST";
export const PRODUCT_CHOOSE_SUCCESS = "PRODUCT_CHOOSE_SUCCESS";
export const PRODUCT_CHOOSE_FAIL = "PRODUCTS_CHOOSE_FAIL";

export const PRODUCT_SELECT_REQUEST = "PRODUCT_SELECT_REQUEST";
export const PRODUCT_SELECT_SUCCESS = "PRODUCT_SELECT_SUCCESS";
export const PRODUCT_SELECT_FAIL = "PRODUCTS_SELECT_FAIL";
